# Generated by Django 5.2.7 on 2025-10-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='hero_bg/')),
                ('btn_text', models.CharField(max_length=150)),
                ('btn_link', models.TextField()),
            ],
        ),
    ]
