# Generated by Django 5.2.7 on 2025-10-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_leaders'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaders',
            name='image',
            field=models.ImageField(default='images/logo (3).jpeg', upload_to='leaders_img/'),
        ),
    ]
