# Generated by Django 5.2.7 on 2025-10-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_leaders_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bible_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_img/')),
                ('scriptures', models.CharField(max_length=200)),
                ('passage', models.CharField(max_length=800)),
                ('message', models.CharField(max_length=1500)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
