# Generated by Django 5.2.7 on 2025-10-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bible_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bible_post',
            name='image',
            field=models.ImageField(default='image/logo (1).jpeg', upload_to='post_img/'),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='image',
            field=models.ImageField(default='image/hero_img (1).jpeg', upload_to='hero_bg/'),
        ),
    ]
