# Generated by Django 5.2.7 on 2025-10-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bible_post_image_alter_herocontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaders',
            name='image',
            field=models.ImageField(default='images/person.jpg', upload_to='leaders_img/'),
        ),
    ]
