# Generated by Django 5.2.7 on 2025-10-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_leaders_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('announcement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Belief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/logo (1).jpeg', upload_to='belief_img/')),
                ('name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/person.jpg', upload_to='testifiers_img/')),
                ('topic', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('testimony', models.TextField()),
                ('testifier', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/logo (1).jpeg', upload_to='testifiers_img/')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('duty', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=800)),
            ],
        ),
    ]
