# Generated by Django 5.2.7 on 2025-10-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_announcement_belief_testimony_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='leader',
            field=models.CharField(default='Ejiofor', max_length=250),
        ),
    ]
