# Generated by Django 5.2.7 on 2025-10-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_unit_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(default='images\\person.jpg', upload_to='testifiers_img/'),
        ),
    ]
