# Generated by Django 5.2.7 on 2025-10-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_testimony_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(default='image/logo (1).jpeg', upload_to='testifiers_img/'),
        ),
    ]
