# Generated by Django 5.2.7 on 2025-10-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_testimony_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bible_post',
            name='image',
            field=models.ImageField(default='images/logo (1).jpeg', upload_to='post_img/'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(default='images/person.jpg', upload_to='testifiers_img/'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(default='images/logo (1).jpeg', upload_to='testifiers_img/'),
        ),
    ]
