# Generated by Django 5.2.6 on 2025-11-18 23:20

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_bible_post_image_alter_testimony_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiblePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptures', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='bible_image')),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='hero_image')),
                ('btn_text', models.CharField(default='Learn More', max_length=50)),
                ('btn_link', models.CharField(default='#', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='leader_image')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MinistryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duty', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('leader', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='unit_image')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Bible_Post',
        ),
        migrations.DeleteModel(
            name='HeroContent',
        ),
        migrations.DeleteModel(
            name='Leaders',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AlterModelOptions(
            name='belief',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='announcement_image'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='belief',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='belief',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimony',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='belief',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='belief',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='belief_image'),
        ),
        migrations.AlterField(
            model_name='belief',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='testimony_image'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='testifier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
