# Generated by Django 5.2.6 on 2025-11-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_biblepost_heroslide_leader_ministryunit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='LFC Teens Byazhin', max_length=200)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('service_times', models.TextField(help_text='Enter service times with days and times')),
            ],
            options={
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.AddField(
            model_name='leader',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ministryunit',
            name='leader_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
