# Generated by Django 5.2.6 on 2025-11-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_contactinfo_leader_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='whatsapp_number',
        ),
    ]
