# Generated by Django 5.2.6 on 2025-11-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_leader_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='is_counselor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leader',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
