# Generated by Django 5.2.6 on 2025-11-24 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_leader_is_counselor_leader_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblepost',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bible_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reviews', to='app.biblepost')),
            ],
            options={
                'unique_together': {('bible_post', 'reviewer_id')},
            },
        ),
    ]
